package lab6_miguelrojas;

import java.io.UnsupportedEncodingException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Inicio extends javax.swing.JFrame {
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        au.cargarArchivoU();
        for (int i = 0; i < au.getListaUsuarios().size(); i++) {
            System.out.println(au.getUser(i));
        }
        
        for (int i = 0; i < au.getListaPasswords().size(); i++) {
            System.out.println(au.getPassword(i));
        }

        //Agregar Nombres a la lista de Chat
        if (au.getListaUsuarios().isEmpty()) {
            //do nothing
        } else {
            refrescarListaContactos();
        }
        
        /* int ascii = 'a';
        System.out.println(ascii); */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUsuario = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        jb_crearUsuario = new javax.swing.JButton();
        jd_chat = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_contactos = new javax.swing.JList<>();
        jb_send = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_chat = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_username_Ingresar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pf_password_Ingresar = new javax.swing.JPasswordField();
        jb_crearC = new javax.swing.JButton();
        jb_login = new javax.swing.JButton();

        jLabel5.setText("Crear Usuario");

        jLabel6.setText("Nombre Completo ");

        jLabel7.setText("Usuario");

        jLabel8.setText("Contraseña");

        jLabel9.setText("Fecha de Nacimiento");

        jb_crearUsuario.setText("Crear Usuario");
        jb_crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_crearUsuario)
                .addGap(119, 119, 119))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre)
                            .addComponent(tf_usuario)
                            .addComponent(pf_password)
                            .addComponent(dc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jb_crearUsuario)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jd_crearUsuarioLayout = new javax.swing.GroupLayout(jd_crearUsuario.getContentPane());
        jd_crearUsuario.getContentPane().setLayout(jd_crearUsuarioLayout);
        jd_crearUsuarioLayout.setHorizontalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_crearUsuarioLayout.setVerticalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 255, 153));
        jPanel3.setForeground(new java.awt.Color(0, 255, 204));

        jLabel10.setText("Contactos");

        jScrollPane1.setViewportView(jl_contactos);

        jb_send.setText("Send");
        jb_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_sendMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jb_send, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jb_send, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane2.setViewportView(ta_mensaje);

        ta_chat.setColumns(20);
        ta_chat.setRows(5);
        jScrollPane3.setViewportView(ta_chat);

        jLabel11.setText("Chat");

        jLabel12.setText("Escribir Mensaje");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jd_chatLayout = new javax.swing.GroupLayout(jd_chat.getContentPane());
        jd_chat.getContentPane().setLayout(jd_chatLayout);
        jd_chatLayout.setHorizontalGroup(
            jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_chatLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jd_chatLayout.setVerticalGroup(
            jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LAB6_Miguel Rojas");

        jLabel2.setText("Usuario");

        jLabel4.setText("Contraseña");

        jb_crearC.setText("Crear Cuenta");
        jb_crearC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCMouseClicked(evt);
            }
        });

        jb_login.setText("Iniciar Sesion");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_username_Ingresar)
                                    .addComponent(pf_password_Ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_crearC)
                                .addGap(141, 141, 141)
                                .addComponent(jb_login))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_username_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pf_password_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crearC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCMouseClicked
        // TODO add your handling code here:

        jd_crearUsuario.setModal(true);
        jd_crearUsuario.pack();
        jd_crearUsuario.setLocationRelativeTo(this);
        jd_crearUsuario.setVisible(true);
    }//GEN-LAST:event_jb_crearCMouseClicked

    private void jb_crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearUsuarioMouseClicked
        // TODO add your handling code here:

        String nombre = null,
                user = null,
                password = null,
                fecha_nacimiento = null;
        Date fecha = null;
        SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
        boolean crear = true;
        //Validar todos los datos ingresados

        //Nombre
        if (tf_nombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearUsuario, "Debe ingresar un nombre");
            crear = false;
        } else {
            nombre = tf_nombre.getText();
        }
        //User
        if (tf_usuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearUsuario, "Debe ingresar un nombre de usuario");
            crear = false;
        } else {
            user = tf_usuario.getText();
        }
        //Password
        if (pf_password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearUsuario, "Debe ingresar una contraseña");
            crear = false;
        } else {
            password = pf_password.getText();
        }
        //Fecha
        fecha = dc_fecha.getDate();
        
        if (fecha == null) {
            JOptionPane.showMessageDialog(jd_crearUsuario, "Debe elegir una fecha de nacimiento");
            crear = false;
            
        } else {
            fecha_nacimiento = sd.format(fecha);
        }

        //Verificar que el usuario sea unico
        if (au.getListaUsername().isEmpty()) {
            //do nothing
        } else {
            if (au.getListaUsername().contains(user)) {
                JOptionPane.showMessageDialog(jd_crearUsuario, "Debe cambiar su nombre de usuario");
                crear = false;
                tf_usuario.setText("");
            }
        }
        //Verificar edad  
        if (crear) {
            try {
                Usuario u = new Usuario(nombre, user, password, fecha_nacimiento);
                
                au.setUsername(user);//Agregar a Lista de Usuario
                au.setPassword(password);//Agregar a Lista de Contraseñas
                au.getListaUsuarios().add(u);
                au.escribirArchivoU();
                JOptionPane.showMessageDialog(jd_crearUsuario, "Usuario creado con Exito!!");
                tf_nombre.setText("");
                tf_usuario.setText("");
                pf_password.setText("");
                dc_fecha.setDate(null);
                jd_crearUsuario.dispose();
                refrescarListaContactos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jd_crearUsuario, "Ocurrio un Error desconocido");
            }
        }
    }//GEN-LAST:event_jb_crearUsuarioMouseClicked

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:
        String user_Ingresar = null,
                pass_Ingresar = null;
        
        boolean iniciar = true;
        if (au.getListaUsuarios().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe ningun usuario");
            iniciar = false;
        }
        
        if (tf_username_Ingresar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar un nombre de usuario");
            iniciar = false;
        } else {
            user_Ingresar = tf_username_Ingresar.getText();
        }
        
        if (pf_password_Ingresar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar una contraseña");
            iniciar = false;
        } else {
            pass_Ingresar = pf_password_Ingresar.getText();
        }
        
        if (au.getListaUsername().contains(user_Ingresar)) {
            //do nothin
        } else {
            JOptionPane.showMessageDialog(this, "Usuario incorrecto o no existe");
            iniciar = false;
            tf_username_Ingresar.setText("");
        }
        if (au.getListaPasswords().contains(pass_Ingresar)) {
            //do nothing
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña Incorrecta o no Existe");
            iniciar = false;
            pf_password_Ingresar.setText("");
        }
        
        if (iniciar) {
            try {
                JOptionPane.showMessageDialog(this, "Ingreso Exitosamente");
                jd_chat.setModal(true);
                jd_chat.pack();
                jd_chat.setLocationRelativeTo(this);
                jd_chat.setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
            }
            
        }

    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_sendMouseClicked
        // TODO add your handling code here:
        char num = ' ';
        String oracion = ta_mensaje.getText().substring(0, ta_mensaje.getText().length() - 2);
        if (ta_mensaje.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_chat, "Debe Escribir algo ");
        } else {
            num = ta_mensaje.getText().charAt(ta_mensaje.getText().length() - 1);
            
        }
        try {

            //Cifra 1
            if (num == '1') {
                System.out.println("No lo termine");
            }
            //Cifra 2
            if (num == '2') {
                String text_return = cifra2();
                String texto = "";
                texto +=tf_username_Ingresar.getText() +":" + oracion +"\n"+ "Maquina: " + text_return;
                ta_chat.setText(texto);
                ta_mensaje.setText("");
            }
            //Cifra 3
            if (num == '3') {
               
                String text_return =  cifra3();
                String mensajes = "";
                mensajes += tf_username_Ingresar.getText() +":" + oracion +"\n"+ "Maquina: " + text_return;
                ta_chat.setText(mensajes);
                ta_mensaje.setText("");
                
            }
            //Cifra 4
            if (num == '4') {
                System.out.println("No lo termine");
                
            }
            
        } catch (NullPointerException e) {
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_sendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_crearC;
    private javax.swing.JButton jb_crearUsuario;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_send;
    private javax.swing.JDialog jd_chat;
    private javax.swing.JDialog jd_crearUsuario;
    private javax.swing.JList<String> jl_contactos;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPasswordField pf_password_Ingresar;
    private javax.swing.JTextArea ta_chat;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_username_Ingresar;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    Admin_usuario au = new Admin_usuario("./Users");
    
    public void refrescarListaContactos() {
        
        DefaultListModel model = new DefaultListModel();
        
        for (Usuario lu : au.getListaUsuarios()) {
            model.addElement(lu);
        }
        jl_contactos.setModel(model);
    }
    
    public void cifra1() {
        String oracion = ta_mensaje.getText().substring(0, ta_mensaje.getText().length() - 2);
        char espacio = ' ';
        for (int i = 0; i < oracion.length(); i++) {
            
                
            
        }
        
        
    }
    
    public String cifra2() throws UnsupportedEncodingException {
        String oracion = ta_mensaje.getText().substring(0, ta_mensaje.getText().length() - 2);
        int length = oracion.length();
        String temp = "";
        for (int i = 0; i < length; i++) {
            char letra = oracion.charAt(i);
            int ascii =(int) letra;
            temp += ascii;
        }
        return temp;
    }
    
    public String cifra3() {
        
        String oracion = ta_mensaje.getText().substring(0, ta_mensaje.getText().length() - 2);
        System.out.println("---\n" + oracion);
        for (int i = 0; i < oracion.length(); i++) {
            char letra = oracion.charAt(i);
            if (letra == 'a') {
                oracion = oracion.replace('a','z');
            } else if (letra == 'A') {
                oracion = oracion.replace('A', 'Z');
            }
            //B
            else if (letra == 'b') {
                 oracion = oracion.replace('b', 'y');
            }
            else if (letra == 'B') {
                 oracion = oracion.replace('B', 'Y');
            }
            //C
            else if (letra == 'c') {
                 oracion = oracion.replace('c', 'x');
            }else if (letra == 'C') {
                 oracion = oracion.replace('C', 'X');
            }
            //D
            else if (letra == 'd') {
                 oracion = oracion.replace('d', 'w');
            }else if (letra == 'D') {
                 oracion = oracion.replace('D', 'W');
            }
            //E
            else if (letra == 'e') {
                 oracion = oracion.replace('e', 'v');
            }else if (letra == 'E') {
                 oracion = oracion.replace('E', 'V');
            }
            //F
            else if (letra == 'f') {
                 oracion = oracion.replace('f', 'u');
            }else if (letra == 'F') {
                 oracion = oracion.replace('F', 'U');
            }
            //G
            else if (letra == 'g') {
                 oracion = oracion.replace('g', 't');
            }else if (letra == 'G') {
                 oracion = oracion.replace('G', 'T');
            }
            //H
            else if (letra == 'h') {
                 oracion = oracion.replace('h', 's');
            }else if (letra == 'H') {
                 oracion = oracion.replace('H', 'S');
            }
            //I
            else if (letra == 'i') {
                 oracion = oracion.replace('i', 'r');
            }else if (letra == 'I') {
                 oracion = oracion.replace('I', 'R');
            }
            //J
            else if (letra == 'j') {
                 oracion = oracion.replace('j', 'q');
            }else if (letra == 'J') {
                 oracion = oracion.replace('J', 'Q');
            }
            //K
            else if (letra == 'k') {
                 oracion = oracion.replace('k', 'p');
            }else if (letra == 'K') {
                 oracion = oracion.replace('K', 'P');
            }
            //L
            else if (letra == 'l') {
                 oracion = oracion.replace('l', 'o');
            }else if (letra == 'L') {
                 oracion = oracion.replace('L', 'O');
            }
            //M
            else if (letra == 'm') {
                 oracion = oracion.replace('m', 'n');
            }else if (letra == 'M') {
                 oracion = oracion.replace('M', 'N');
            }
            //N
            else if (letra == 'n') {
                 oracion = oracion.replace('n', 'm');
            }else if (letra == 'N') {
                 oracion = oracion.replace('N', 'M');
            }
            //O
            else if (letra == 'o') {
                 oracion = oracion.replace('o', 'l');
            }else if (letra == 'O') {
                 oracion = oracion.replace('O', 'L');
            }
            //P
            else if (letra == 'p') {
                 oracion = oracion.replace('p', 'k');
            }else if (letra == 'p') {
                 oracion = oracion.replace('P', 'K');
            }
            //Q
            else if (letra == 'q') {
                 oracion = oracion.replace('q', 'j');
            }else if (letra == 'Q') {
                 oracion = oracion.replace('Q', 'J');
            }
            //R
            else if (letra == 'r') {
                 oracion = oracion.replace('r', 'i');
            }else if (letra == 'R') {
                 oracion = oracion.replace('R', 'I');
            }
            //S
            else if (letra == 's') {
                 oracion = oracion.replace('s', 'h');
            }else if (letra == 'S') {
                 oracion = oracion.replace('S', 'H');
            }
            //T
            else if (letra == 't') {
                 oracion = oracion.replace('t', 'g');
            }else if (letra == 'T') {
                 oracion = oracion.replace('T', 'G');
            }
            //U
            else if (letra == 'u') {
                 oracion = oracion.replace('u', 'f');
            }else if (letra == 'U') {
                 oracion = oracion.replace('U', 'F');
            }
            //V
            else if (letra == 'v') {
                 oracion = oracion.replace('v', 'e');
            }else if (letra == 'V') {
                 oracion = oracion.replace('V', 'E');
            }
            //W
            else if (letra == 'w') {
                 oracion = oracion.replace('w', 'd');
            }else if (letra == 'W') {
                 oracion = oracion.replace('W', 'D');
            }
            //X
            else if (letra == 'x') {
                 oracion = oracion.replace('x', 'c');
            }else if (letra == 'X') {
                 oracion = oracion.replace('X', 'C');
            }
            //Y
            else if (letra == 'y') {
                 oracion = oracion.replace('y', 'b');
            }else if (letra == 'Y') {
                 oracion = oracion.replace('Y', 'B');
            }
            //Z
            else if (letra == 'z') {
                 oracion = oracion.replace('z', 'a');
            }else if (letra == 'Z') {
                 oracion = oracion.replace('z', 'A');
            }
        }
        System.out.println("---\n" + oracion);
        return oracion;
    }
    
    public void cifra4() {
        
    }
}
